<?php
//
// File generated by Dolibarr installer 19.0.2
// MODIFIED FOR ROBUST NGROK SUPPORT (SSL + HOST HEADERS)
//

// --------------------------------------------------------------------
// DYNAMIC URL & HOST DETECTION
// --------------------------------------------------------------------
$proto = 'http';
// 1. Detect HTTPS (Secure connection)
if ((!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') || 
    (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https')) {
    $proto = 'https';
}

// 2. Detect Real Host (Fixes Cookie Domain Mismatch)
$host = $_SERVER['HTTP_HOST'];
if (!empty($_SERVER['HTTP_X_FORWARDED_HOST'])) {
    $host = $_SERVER['HTTP_X_FORWARDED_HOST'];
}

// 3. Construct the Main URL
$dolibarr_main_url_root = $proto . "://" . $host;

// 4. Force HTTPS settings if we detected HTTPS
// This ensures cookies are marked 'Secure' if needed, but prevents redirect loops
$dolibarr_main_force_https = '0'; 
// --------------------------------------------------------------------


$dolibarr_main_document_root='/var/www/html';
$dolibarr_main_url_root_alt='/custom';
$dolibarr_main_document_root_alt='/var/www/html/custom';
$dolibarr_main_data_root='/var/www/html/documents';
$dolibarr_main_db_host='dolibarr-db';
$dolibarr_main_db_port='3306';
$dolibarr_main_db_name='dolibarr';
$dolibarr_main_db_prefix='llx_';
$dolibarr_main_db_user='dolibarr';
$dolibarr_main_db_pass='supersecretpassword';
$dolibarr_main_db_type='mysqli';
$dolibarr_main_db_character_set='utf8';
$dolibarr_main_db_collation='utf8_unicode_ci';

// Authentication settings
$dolibarr_main_authentication='dolibarr';

// Security settings
$dolibarr_main_prod='0';
$dolibarr_main_restrict_os_commands='mariadb-dump, mariadb, mysqldump, mysql, pg_dump, pgrestore, clamdscan, clamscan.exe';
$dolibarr_nocsrfcheck='0';
$dolibarr_main_instance_unique_id='4a7cbe85500bf1190c22f3051ff708d7';
$dolibarr_mailing_limit_sendbyweb='0';
$dolibarr_mailing_limit_sendbycli='0';

$dolibarr_main_distrib='standard';